//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXA.CM.Extensions.DXAResolver.Editors {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DXA_CM_Extensions_DXAResolver_Editors_Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DXA_CM_Extensions_DXAResolver_Editors_Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DXA.CM.Extensions.DXAResolver.Editors.Resources.DXA.CM.Extensions.DXAResolv" +
                            "er.Editors.Strings", typeof(DXA_CM_Extensions_DXAResolver_Editors_Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CR_Close {
            get {
                return ResourceManager.GetString("CR_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DXA Resolver: Unable to load configuration.
        /// </summary>
        internal static string CR_ConfigurationLoadFailed {
            get {
                return ResourceManager.GetString("CR_ConfigurationLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DXA Resolver: Configuration has been saved..
        /// </summary>
        internal static string CR_ConfigurationSaved {
            get {
                return ResourceManager.GetString("CR_ConfigurationSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DXA Resolver: Unable to save configuration.
        /// </summary>
        internal static string CR_ConfigurationSaveFailed {
            get {
                return ResourceManager.GetString("CR_ConfigurationSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DXA Resolver.
        /// </summary>
        internal static string CR_DXAResolver {
            get {
                return ResourceManager.GetString("CR_DXAResolver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DXA Settings.
        /// </summary>
        internal static string CR_EditDXASettingsDialogTitle {
            get {
                return ResourceManager.GetString("CR_EditDXASettingsDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DXA Resolver Recursion Depth.
        /// </summary>
        internal static string CR_RecurseDepth {
            get {
                return ResourceManager.GetString("CR_RecurseDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DXA Resolver: Recursion Depth can not be empty..
        /// </summary>
        internal static string CR_RecurseDepthCanNotBeEmpty {
            get {
                return ResourceManager.GetString("CR_RecurseDepthCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter an integer, such as &quot;100&quot; for a depth of 100 linked components. For infinite recursion, enter &quot;-1&quot;.
        /// </summary>
        internal static string CR_RecurseDepthHint {
            get {
                return ResourceManager.GetString("CR_RecurseDepthHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DXA Resolver: The value for Recursion Depth couldn&apos;t be less than -1..
        /// </summary>
        internal static string CR_RecurseDepthLessThanAllowed {
            get {
                return ResourceManager.GetString("CR_RecurseDepthLessThanAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DXA Resolver: The value for Recursion Depth must be an integer..
        /// </summary>
        internal static string CR_RecurseDepthShouldBeNumeric {
            get {
                return ResourceManager.GetString("CR_RecurseDepthShouldBeNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string CR_Save {
            get {
                return ResourceManager.GetString("CR_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DXA Resolver Publishing Settings.
        /// </summary>
        internal static string CR_Settings {
            get {
                return ResourceManager.GetString("CR_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DXA Settings.
        /// </summary>
        internal static string CR_ShowSettings {
            get {
                return ResourceManager.GetString("CR_ShowSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show DXA Resolver Settings Dialog.
        /// </summary>
        internal static string CR_ShowSettingsDialog {
            get {
                return ResourceManager.GetString("CR_ShowSettingsDialog", resourceCulture);
            }
        }
    }
}
