//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXA.CM.Extensions.CustomResolver.Editors {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DXA_CM_Extensions_CustomResolver_Editors_Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DXA_CM_Extensions_CustomResolver_Editors_Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DXA.CM.Extensions.CustomResolver.Editors.Resources.DXA.CM.Extensions.CustomResolv" +
                            "er.Editors.Strings", typeof(DXA_CM_Extensions_CustomResolver_Editors_Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CR_Close {
            get {
                return ResourceManager.GetString("CR_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DXA Custom Resolver.
        /// </summary>
        internal static string CR_DXACustomResolver {
            get {
                return ResourceManager.GetString("CR_DXACustomResolver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DXA Settings.
        /// </summary>
        internal static string CR_EditDXASettingsDialogTitle {
            get {
                return ResourceManager.GetString("CR_EditDXASettingsDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurse Depth.
        /// </summary>
        internal static string CR_RecurseDepth {
            get {
                return ResourceManager.GetString("CR_RecurseDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string CR_Save {
            get {
                return ResourceManager.GetString("CR_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Resolver Publishing Settings.
        /// </summary>
        internal static string CR_Settings {
            get {
                return ResourceManager.GetString("CR_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DXA Settings.
        /// </summary>
        internal static string CR_ShowSettings {
            get {
                return ResourceManager.GetString("CR_ShowSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show DXA Custom Resolver Settings Dialog.
        /// </summary>
        internal static string CR_ShowSettingsDialog {
            get {
                return ResourceManager.GetString("CR_ShowSettingsDialog", resourceCulture);
            }
        }
    }
}
